version: "3.8"

services:
  api-postgres:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data

  api-pg-admin: 
    image: dpage/pgadmin4:latest
    platform: linux/amd64
    depends_on: 
      - api-postgres 
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports: 
      - "8080:80"
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin

  api-php:
    image: php:8.2-apache
    container_name: api-php
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./php-app:/var/www/html
    depends_on:
      - api-postgres

networks:
  default:
    name: api-network
    external: true
